-- Blog Content Fixes - Address All Identified Issues (FIXED VERSION)
-- Run this script to fix existing blog content issues

BEGIN;

-- Fix 1: Remove HTML code markers from content start and end
UPDATE blog_posts 
SET content = REGEXP_REPLACE(
    REGEXP_REPLACE(content, '^```html\s*', '', 'g'), 
    '\s*```\s*$', '', 'g'
)
WHERE content LIKE '%```html%' OR content LIKE '%```%';

-- Fix 2: Remove full HTML document structure (DOCTYPE, html, head, body tags)
UPDATE blog_posts 
SET content = REGEXP_REPLACE(
    REGEXP_REPLACE(
        REGEXP_REPLACE(
            REGEXP_REPLACE(content, '<!DOCTYPE html>\s*<html[^>]*>\s*<head[^>]*>.*?</head>\s*<body[^>]*>', '', 'gs'),
            '</body>\s*</html>\s*$', '', 'gs'
        ),
        '<article>\s*', '', 'g'
    ),
    '\s*</article>', '', 'g'
)
WHERE content LIKE '%<!DOCTYPE html>%' OR content LIKE '%<html%' OR content LIKE '%<body%';

-- Fix 3: Remove AI disclaimers and notes about fictional content
UPDATE blog_posts 
SET content = REGEXP_REPLACE(
    REGEXP_REPLACE(
        REGEXP_REPLACE(content, 'Note:.*?(fictional|illustrative purposes).*?(\.|$)', '', 'gs'),
        'Disclaimer:.*?(generated|AI|artificial intelligence).*?(\.|$)', '', 'gsi'
    ),
    '(This content was|Content generated|Generated by).*?(AI|artificial intelligence|ChatGPT|GPT).*?(\.|$)', '', 'gsi'
)
WHERE content ~* '(fictional|illustrative purposes|generated|AI|artificial intelligence|ChatGPT|GPT|disclaimer)';

-- Fix 4: Remove "(DEPLOYED)" and variations from titles
UPDATE blog_posts 
SET title = REGEXP_REPLACE(title, '\s*\(DEPLOYED\)\s*', '', 'gi'),
    slug = REGEXP_REPLACE(slug, '-deployed$', '', 'g')
WHERE title ~* '\(deployed\)';

-- Fix 5: Update internal links to correct Arzani URLs
-- Replace /marketplace with /marketplace2 for business listings
UPDATE blog_posts 
SET content = REPLACE(content, 'href="/marketplace"', 'href="/marketplace2"')
WHERE content LIKE '%href="/marketplace"%';

UPDATE blog_posts 
SET content = REPLACE(content, 'href="www.arzani.co.uk/marketplace"', 'href="www.arzani.co.uk/marketplace2"')
WHERE content LIKE '%href="www.arzani.co.uk/marketplace"%';

-- Fix 6: Add proper business valuation links
UPDATE blog_posts 
SET content = REGEXP_REPLACE(
    content, 
    '(business valuation)(?!\s*</a>)', 
    '<a href="/business-valuation" class="internal-link">\1</a>', 
    'gi'
)
WHERE content ~* 'business valuation' 
AND content !~ 'business valuation</a>';

-- Fix 7: Update "learn more" links to point to marketplace-landing
UPDATE blog_posts 
SET content = REGEXP_REPLACE(
    content, 
    '(learn more)(?!\s*</a>)', 
    '<a href="/marketplace-landing" class="internal-link">\1</a>', 
    'gi'
)
WHERE content ~* 'learn more' 
AND content !~ 'learn more</a>';

-- Fix 8: Update "Arzani marketplace" references
UPDATE blog_posts 
SET content = REPLACE(content, 'Arzani marketplace', '<a href="/marketplace2" class="internal-link">Arzani marketplace</a>')
WHERE content LIKE '%Arzani marketplace%' 
AND content NOT LIKE '%Arzani marketplace</a>%';

-- Fix 9: Clean up any remaining AI-generated disclaimers in conclusions
UPDATE blog_posts 
SET content = REGEXP_REPLACE(
    content, 
    '<h2>Conclusion</h2>\s*<p>.*?(generated|AI|prompt|instruction).*?</p>', 
    '<h2>Conclusion</h2>\n<p>Making informed decisions about your business requires expert guidance and reliable market data.</p>', 
    'gsi'
)
WHERE content ~* '<h2>Conclusion</h2>.*?(generated|AI|prompt|instruction)';

-- Fix 10: Ensure all links have proper CSS classes
UPDATE blog_posts 
SET content = REGEXP_REPLACE(
    content, 
    '<a href="(/[^"]*)"([^>]*)>', 
    '<a href="\1" class="internal-link"\2>', 
    'g'
)
WHERE content ~ '<a href="(/[^"]*)"[^>]*>' 
AND content !~ 'class="[^"]*link[^"]*"';

-- Fix 11: Clean up any remaining HTML formatting issues
UPDATE blog_posts 
SET content = REGEXP_REPLACE(
    REGEXP_REPLACE(
        REGEXP_REPLACE(content, '\s+', ' ', 'g'),
        '(<h[1-6][^>]*>)\s+', '\1', 'g'
    ),
    '\s+(</h[1-6]>)', '\1', 'g'
)
WHERE content ~ '\s{2,}';

-- Fix 12: Add tracking using existing JSONB column
-- Update content_links to track these posts as automated and cleaned
UPDATE blog_posts 
SET content_links = COALESCE(content_links::jsonb, '{}'::jsonb) || 
    jsonb_build_object(
        'automated_generation', true,
        'content_cleaned', true,
        'last_updated', NOW()::text,
        'fixes_applied', jsonb_build_array(
            'html_markers_removed',
            'ai_disclaimers_removed', 
            'internal_links_fixed',
            'deployed_tags_removed'
        )
    )
WHERE status IN ('Published', 'published');

-- Fix 13: Update CTA links to use correct URLs
UPDATE blog_posts 
SET cta_link = '/marketplace2'
WHERE cta_link = '/marketplace';

COMMIT;

-- Verification queries to check the fixes
SELECT 'Posts with HTML markers' as check_type, COUNT(*) as count
FROM blog_posts 
WHERE content LIKE '%```%';

SELECT 'Posts with DEPLOYED in title' as check_type, COUNT(*) as count  
FROM blog_posts 
WHERE title ~* '\(deployed\)';

SELECT 'Posts with AI disclaimers' as check_type, COUNT(*) as count
FROM blog_posts 
WHERE content ~* '(fictional|illustrative purposes|generated|AI|artificial intelligence)';

SELECT 'Posts with old marketplace links' as check_type, COUNT(*) as count
FROM blog_posts 
WHERE content LIKE '%href="/marketplace"%' AND content NOT LIKE '%href="/marketplace2"%';

SELECT 'Posts with content_links tracking' as check_type, COUNT(*) as count
FROM blog_posts 
WHERE content_links ? 'automated_generation';
