# Rollback HTML Cleanup Changes - PowerShell Script
# This script helps you revert the HTML cleanup changes

param(
    [string]$DatabaseUrl = $env:DATABASE_URL,
    [string]$BackupPath = "",
    [switch]$ShowAffectedPosts = $false,
    [switch]$DeleteAndRegenerate = $false,
    [switch]$RestoreFromBackup = $false
)

Write-Host "HTML Cleanup Rollback Assistant" -ForegroundColor Yellow
Write-Host "================================" -ForegroundColor Yellow

# Check if we have database URL
if (-not $DatabaseUrl) {
    Write-Host "DATABASE_URL environment variable not found" -ForegroundColor Red
    Write-Host "Please set DATABASE_URL or provide it as a parameter" -ForegroundColor Yellow
    exit 1
}

if ($ShowAffectedPosts) {
    Write-Host "Showing posts affected by the HTML cleanup..." -ForegroundColor Blue
    
    $query = @"
SELECT 
    id, 
    title, 
    updated_at,
    LENGTH(content) as content_length
FROM blog_posts 
WHERE updated_at > NOW() - INTERVAL '2 hours'
ORDER BY updated_at DESC;
"@
    
    psql "$DatabaseUrl" -c "$query"
    exit 0
}

if ($RestoreFromBackup -and $BackupPath) {
    Write-Host "Restoring from backup: $BackupPath" -ForegroundColor Blue
    
    if (-not (Test-Path $BackupPath)) {
        Write-Host "Backup file not found: $BackupPath" -ForegroundColor Red
        exit 1
    }
    
    Write-Host "WARNING: This will overwrite your current database!" -ForegroundColor Red
    $confirm = Read-Host "Type 'YES' to continue"
    
    if ($confirm -ne "YES") {
        Write-Host "Rollback cancelled." -ForegroundColor Yellow
        exit 0
    }
    
    try {
        Write-Host "Restoring database from backup..." -ForegroundColor Blue
        pg_restore -d "$DatabaseUrl" --clean --if-exists "$BackupPath"
        
        if ($LASTEXITCODE -eq 0) {
            Write-Host "Database restored successfully!" -ForegroundColor Green
        } else {
            Write-Host "Error restoring database" -ForegroundColor Red
            exit 1
        }
    } catch {
        Write-Host "Exception occurred: $($_.Exception.Message)" -ForegroundColor Red
        exit 1
    }
}

if ($DeleteAndRegenerate) {
    Write-Host "WARNING: This will delete recently modified blog posts!" -ForegroundColor Red
    Write-Host "Only posts generated by automation will be affected." -ForegroundColor Yellow
    
    $confirm = Read-Host "Type 'DELETE' to continue"
    
    if ($confirm -ne "DELETE") {
        Write-Host "Operation cancelled." -ForegroundColor Yellow
        exit 0
    }
    
    $deleteQuery = @"
DELETE FROM blog_posts 
WHERE content_links->>'automated_generation' = 'true'
AND updated_at > NOW() - INTERVAL '2 hours';
"@
    
    try {
        Write-Host "Deleting automated posts modified in the last 2 hours..." -ForegroundColor Blue
        $result = psql "$DatabaseUrl" -c "$deleteQuery" 2>&1
        
        if ($LASTEXITCODE -eq 0) {
            Write-Host "Posts deleted successfully!" -ForegroundColor Green
            Write-Host "You can now regenerate them using the blog automation system." -ForegroundColor Blue
        } else {
            Write-Host "Error deleting posts:" -ForegroundColor Red
            Write-Host $result -ForegroundColor Red
            exit 1
        }
    } catch {
        Write-Host "Exception occurred: $($_.Exception.Message)" -ForegroundColor Red
        exit 1
    }
}

if (-not $ShowAffectedPosts -and -not $RestoreFromBackup -and -not $DeleteAndRegenerate) {
    Write-Host ""
    Write-Host "ROLLBACK OPTIONS:" -ForegroundColor Green
    Write-Host "=================" -ForegroundColor Green
    Write-Host ""
    Write-Host "1. Show affected posts:" -ForegroundColor White
    Write-Host "   .\rollback-html-cleanup.ps1 -ShowAffectedPosts" -ForegroundColor Gray
    Write-Host ""
    Write-Host "2. Restore from backup (if you have one):" -ForegroundColor White
    Write-Host "   .\rollback-html-cleanup.ps1 -RestoreFromBackup -BackupPath 'path\to\backup.sql'" -ForegroundColor Gray
    Write-Host ""
    Write-Host "3. Delete and regenerate automated posts:" -ForegroundColor White
    Write-Host "   .\rollback-html-cleanup.ps1 -DeleteAndRegenerate" -ForegroundColor Gray
    Write-Host ""
    Write-Host "4. Manual SQL rollback:" -ForegroundColor White
    Write-Host "   psql `$env:DATABASE_URL -f rollback-html-cleanup.sql" -ForegroundColor Gray
    Write-Host ""
    Write-Host "BACKUP RECOMMENDATIONS:" -ForegroundColor Yellow
    Write-Host "======================" -ForegroundColor Yellow
    Write-Host "Before making changes in the future, create a backup:" -ForegroundColor White
    Write-Host "pg_dump -d `$env:DATABASE_URL > backup_$(Get-Date -Format 'yyyyMMdd_HHmmss').sql" -ForegroundColor Gray
}
